//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardOrder.Preferences.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardOrder.Preferences.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Thickness.
        /// </summary>
        public static string BOARD_THICKNESS_LABEL {
            get {
                return ResourceManager.GetString("BOARD_THICKNESS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards Quantity.
        /// </summary>
        public static string BOARDS_QUANTITY_LABEL {
            get {
                return ResourceManager.GetString("BOARDS_QUANTITY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Impedance.
        /// </summary>
        public static string CONTROLLED_IMPEDANCE_LABEL {
            get {
                return ResourceManager.GetString("CONTROLLED_IMPEDANCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coper Weight on Inner Layers.
        /// </summary>
        public static string COOPER_WEIGHT_ON_INNER_LAYERS_LABEL {
            get {
                return ResourceManager.GetString("COOPER_WEIGHT_ON_INNER_LAYERS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coper Weight on Outer Layers.
        /// </summary>
        public static string COOPER_WEIGHT_ON_OUTER_LAYERS_LABEL {
            get {
                return ResourceManager.GetString("COOPER_WEIGHT_ON_OUTER_LAYERS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux Type.
        /// </summary>
        public static string FLUX_TYPE_LABEL {
            get {
                return ResourceManager.GetString("FLUX_TYPE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC Class.
        /// </summary>
        public static string IPC_CLASS_LABEL {
            get {
                return ResourceManager.GetString("IPC_CLASS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITAR.
        /// </summary>
        public static string ITAR_LABEL {
            get {
                return ResourceManager.GetString("ITAR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Free.
        /// </summary>
        public static string LEAD_FREE_LABEL {
            get {
                return ResourceManager.GetString("LEAD_FREE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MATERIAL_LABEL {
            get {
                return ResourceManager.GetString("MATERIAL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NOTES_LABEL {
            get {
                return ResourceManager.GetString("NOTES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string PROJECT_NAME_LABEL {
            get {
                return ResourceManager.GetString("PROJECT_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silkscreen Color.
        /// </summary>
        public static string SILKSCREEN_COLOR_LABEL {
            get {
                return ResourceManager.GetString("SILKSCREEN_COLOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder Mask Color.
        /// </summary>
        public static string SOLDER_MASK_COLOR_LABEL {
            get {
                return ResourceManager.GetString("SOLDER_MASK_COLOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stackup.
        /// </summary>
        public static string STACKUP_LABEL {
            get {
                return ResourceManager.GetString("STACKUP_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish.
        /// </summary>
        public static string SURFACE_FINISH_LABEL {
            get {
                return ResourceManager.GetString("SURFACE_FINISH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenting for Vias.
        /// </summary>
        public static string TENTING_FOR_VIAS_LABEL {
            get {
                return ResourceManager.GetString("TENTING_FOR_VIAS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string ZIPCODE_LABEL {
            get {
                return ResourceManager.GetString("ZIPCODE_LABEL", resourceCulture);
            }
        }
    }
}
